import {
  LayoutDashboard,
  ClipboardList,
  FileCheck2,
  Receipt,
  User,
  Download,
  Scale,
  TrendingUp,
  BookOpen,
  PenLine,
  UserCheck,
  Users,
  KeyRound,
  Settings,
} from "lucide-react";
import { type SidebarItem } from "@/components/portal/portal-shell";
import { type PortalRole } from "@/lib/pams";

export const sidebarItems: Record<PortalRole, SidebarItem[]> = {
  applicant: [
    { type: "link", label: "Dashboard", href: "/portal/applicant", icon: LayoutDashboard },
    { type: "link", label: "Applications", href: "/portal/applicant/applications", icon: ClipboardList },
    { type: "link", label: "Permits", href: "/portal/applicant/permits", icon: FileCheck2 },
    { type: "link", label: "Invoices", href: "/portal/applicant/invoices", icon: Receipt },
    { type: "divider" },
    { type: "link", label: "Profile", href: "/portal/applicant/profile", icon: User },
  ],
  employee: [
    { type: "link", label: "Dashboard", href: "/portal/employee", icon: LayoutDashboard },
    { type: "link", label: "Applications", href: "/portal/employee/applications", icon: ClipboardList },
    { type: "link", label: "Permits", href: "/portal/employee/permits", icon: FileCheck2 },
    { type: "link", label: "Invoices", href: "/portal/employee/invoices", icon: Receipt },
    { type: "divider" },
    { type: "link", label: "Exports", href: "/portal/employee/exports", icon: Download },
    { type: "divider" },
    { type: "link", label: "Profile", href: "/portal/employee/profile", icon: User },
  ],
  manager: [
    { type: "link", label: "Dashboard", href: "/portal/manager", icon: LayoutDashboard },
    { type: "link", label: "Applications", href: "/portal/manager/applications", icon: ClipboardList },
    { type: "link", label: "Permits", href: "/portal/manager/permits", icon: FileCheck2 },
    { type: "link", label: "Invoices", href: "/portal/manager/invoices", icon: Receipt },
    { type: "divider" },
    { type: "link", label: "Service Catalog", href: "/portal/manager/service-catalog", icon: BookOpen },
    { type: "link", label: "Signatures", href: "/portal/manager/signatures", icon: PenLine },
    { type: "link", label: "Reports", href: "/portal/manager/reports", icon: TrendingUp },
  ],
  minister: [
    { type: "link", label: "Dashboard", href: "/portal/minister", icon: LayoutDashboard },
    { type: "link", label: "Decisions Queue", href: "/portal/minister/decisions", icon: Scale },
    { type: "link", label: "Signed Permits", href: "/portal/minister/permits", icon: FileCheck2 },
    { type: "divider" },
    { type: "link", label: "Reports", href: "/portal/minister/reports", icon: TrendingUp },
  ],
  finance: [
    { type: "link", label: "Dashboard", href: "/portal/finance", icon: LayoutDashboard },
    { type: "link", label: "Invoices", href: "/portal/finance/invoices", icon: Receipt },
    { type: "link", label: "Exports", href: "/portal/finance/exports", icon: Download },
  ],
  admin: [
    { type: "link", label: "Dashboard", href: "/portal/admin", icon: LayoutDashboard },
    { type: "link", label: "Pending Registrations", href: "/portal/admin/registrations", icon: UserCheck },
    { type: "link", label: "User Management", href: "/portal/admin/users", icon: Users },
    { type: "link", label: "Role Access", href: "/portal/admin/roles", icon: KeyRound },
    { type: "divider" },
    { type: "link", label: "Service Catalog", href: "/portal/manager/service-catalog", icon: BookOpen },
    { type: "link", label: "Signatures", href: "/portal/manager/signatures", icon: PenLine },
    { type: "link", label: "Reports", href: "/portal/admin/reports", icon: TrendingUp },
    { type: "divider" },
    { type: "link", label: "System Settings", href: "/portal/admin/settings", icon: Settings },
  ],
};
